### ISSUE TITLE
Ignore/exclude possible?

### ISSUE THREAD

**Issue by booYah187** [Palleri/dockcheck-web#7]
Great work on this tool, I can verify that the gotify notifications work on amd64 and arm64. I was wondering if there was a way to ignore or exclude specific containers, as I have a few containers that I would prefer not to update and don't need the recurring notifications for.

**Comment by Palleri** [comment]
Hi, thank you for testing the gotify. I will add it to the list of tested services.
Ye good idea. I will see what I can do!

**Comment by mag37** [comment]
I've made options for it in the backend-script - it's still in [testing branch](https://github.com/mag37/dockcheck/blob/testing/dockcheck.sh) and I'd gladly receive feedback if anyone test it. 
Will merge it with main asap so @Palleri can can use it if he'd like.

**Comment by Palleri** [comment]
Update. I will start testing this next week. Already prepared the exclude function in my build.

**Comment by booYah187** [comment]
You guys are good, have an icon
![dockcheck](https://user-images.githubusercontent.com/95330381/221442772-486456db-22fb-4e87-8afd-dc42a098fb54.png)

**Comment by Palleri** [comment]
Hi, I just finished the function on my end.
Use the EXCLUDE variable explained down below.

```yml
version: '3.2'
services:
  ...
    environment:
      NOTIFY: "true"
      NOTIFY_URLS: "discord://Dockcheck-web@xxxxx/xxxxxx"
      EXCLUDE: "nginx,plex,prowlarr"
  ...
```

And I just made a slim version of dockcheck container without the webui.
Just a notification service.
Both versions have the EXCLUDE function.
[dockcheck-slim](https://github.com/Palleri/dockcheck-slim)
